services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: tasks/Dockerfile.redis-celery
    container_name: celery_worker
    volumes:
      - ./tasks:/app/tasks
    command: celery -A tasks.tasks.py worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: tasks/Dockerfile.redis-celery
    container_name: celery_beat
    volumes:
      - ./tasks:/app/tasks
    command: celery -A tasks.tasks.py beat --loglevel=info
    depends_on:
      - redis
