# Dockerfile
FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
ENV PYTHONPATH "${PYTHONPATH}:/app"
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first to leverage Docker cache
COPY requirements.txt .

# Install Python dependencies
RUN pip install -r requirements.txt

# Set FLASK_APP to point to main.py
ENV FLASK_ENV=development
ENV FLASK_APP=main.py
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json

# Command to run the application in development mode
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]