services:
  backend-test:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: backend-test-service
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    environment:
      - FLASK_ENV=test
      - FLASK_DEBUG=0
      - DOCKER_MYSQL_PORT=3306
      - DOCKER_MYSQL_HOST=database-test-service
      - DOCKER_MYSQL_USER=kanver_user
      - DOCKER_MYSQL_PASSWORD=kanver_password
      - DOCKER_MYSQL_DB=kanver
    depends_on:
      database-test:
        condition: service_healthy
    expose:
      - "8080"
    command: pytest --disable-warnings --junitxml=test-results.xml
  database-test:
    image: mysql:8.0
    container_name: database-test-service
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=kanver_user
      - MYSQL_PASSWORD=kanver_password
      - MYSQL_DATABASE=kanver
    ports:
      - "3307:3306"  # Use a different port for tests
    expose:
      - "3306"
    volumes:

      - mysql_data:/var/lib/mysql
      - ./database/sql/schema.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      - ./database/sql/load_data.sql:/docker-entrypoint-initdb.d/2-load_data.sql
      - ./database/sql/mark_healthy.sql:/docker-entrypoint-initdb.d/3-mark_healthy.sql
      - ./database/dataset:/var/lib/mysql-files
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysql -h localhost -ukanver_user -pkanver_password -e \"SELECT status FROM kanver.initialization_flag WHERE status='completed' LIMIT 1\""
      ]
      interval: 5s
      retries: 20
      start_period: 10s
      timeout: 2s
volumes:
  mysql_data: