services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: tasks/Dockerfile.redis-celery
    container_name: celery_worker
    volumes:
      - ./tasks:/app/tasks
    command: celery -A tasks.tasks worker --loglevel=info
    environment:
      - DOCKER_MYSQL_PORT=3306
      - DOCKER_MYSQL_HOST=database-service
      - DOCKER_MYSQL_USER=kanver_user
      - DOCKER_MYSQL_PASSWORD=kanver_password
      - DOCKER_MYSQL_DB=kanver
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: tasks/Dockerfile.redis-celery
    container_name: celery_beat
    volumes:
      - ./tasks:/app/tasks
    command: celery -A tasks.tasks beat --loglevel=info
    depends_on:
      - redis
