# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy only necessary files
COPY tasks/ /app/tasks/
COPY database/helper.py /app/database/helper.py
COPY .env.example /app/.env
# Install dependencies
RUN pip install --no-cache-dir -r tasks/requirements.txt