name: PR Build

on:
  pull_request:
    branches:
      - workflow/pr-builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set Up Python and Cache Dependencies
      - name: Cache Python Dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip          # Cache pip's directory
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 3: Build Docker Compose Services
      - name: Build Docker Compose Services
        run: |
          docker-compose build

      # Optional: Verify Services Start Correctly
      - name: Start and List Docker Compose Services
        run: |
          docker-compose up -d
          docker-compose ps

      # Optional: Save Docker Logs (useful for debugging)
      - name: Save Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: docker-compose.logs
