name: Pytest Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set Up Docker
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Copy .env File (if needed)
      - name: Copy .env File
        run: |
          cp .env.example .env || (echo "No .env.example found, exiting..." && exit 1)

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test
