name: Pytest Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Copy .env File (if needed)
      - name: Copy .env File
        run: |
          cp .env.example .env || (echo "No .env.example found, exiting..." && exit 1)

      # Step 3: Run Docker Compose
      - name: Run tests
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
          up-flags: |
                    --build
                    --abort-on-container-exit
                    --exit-code-from backend
          down-flags: |
                    -v
